name: Check links
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config lychee.toml
            --no-progress
            --verbose
            README.md


